--CREATE DATABASE Songify

CREATE TABLE Genre(
	GenreId INT PRIMARY KEY,
	[Name] VARCHAR(255) NOT NULL
)

CREATE TABLE Song(
	SongId INT PRIMARY KEY IDENTITY,
	Title VARCHAR NOT NULL,
	ReleasedDate DATETIMEOFFSET NOT NULL,

	GenreId INT NOT NULL
		CONSTRAINT FK_Song_Genre FOREIGN KEY REFERENCES Genre,

	CreatedAt DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET(),
	CreatedBy VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
	UpdatedAt DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET(),
	UpdatedBy VARCHAR(255) NOT NULL DEFAULT 'SYSTEM'
)

SELECT * FROM Song
SELECT * FROM Genre